# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq swig python-dev libxml2-dev libxmlsec1-dev
        pip install --force-reinstall --no-binary lxml lxml
        pip install .
        pip install -e ".[test]"

    - name: Lint
      run: |
        #pycodestyle tests/src/OneLogin/saml2_tests/*.py demo-flask/*.py demo-django/*.py src/onelogin/saml2/*.py --config=tests/pep8.rc
        #pyflakes src/onelogin/saml2 demo-django demo-flask tests/src/OneLogin/saml2_tests
        flake8 --ignore E226,E302,E41,E731,E501,C901,W504

    - name: Test
      run: |
        coverage run --source=src/onelogin/saml2 --rcfile=tests/coverage.rc setup.py tes

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: .coverage


  coveralls:
    runs-on: ubuntu-20.04
    environment: CI
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq swig python-dev libxml2-dev libxmlsec1-dev
        pip install coveralls==3.3.1 requests coverage[toml]
    
    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
        path: .coverage

    - name: Upload coverage data to coveralls.io
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        pip install coveralls==3.3.1 requests coverage[toml]
        coverage report -m --rcfile=tests/coverage.rc
        coveralls --service=github
