# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq swig python-dev libxml2-dev libxmlsec1-dev
        make install-req
        make install-test

    - name: Test
      run: |
        make pytest
        make pycodestyle
        make flake8       
